In [2]:
import numpy as np
from time import time

## Comparing non-vectorized and vectorized versions

In [3]:
def my_dot(a, b):
    
    """
    Compute the dot product of two vectors
    
    Args:
        a (ndarray (n,)): input vector
        b (ndarray (n,)): input vector with same dimension as a
        
    Returns:
        x (scalar):
    """
    x = 0
    for i in range(len(a)):
        x = x + a[i] * b[i]
    return x    

In [4]:
b = np.random.rand(10000000)
a = np.random.rand(10000000)

start = time()
c = my_dot(a, b)
end = time()

print(f"my_dot(a,b) = {c:.4f}")
print(f"Loop version duration: {1000*(end-start):.4f} ms")

start = time()
c = np.dot(a, b)
end = time()

print(f"np.dot(a,b) = {c:.4f}")
print(f"Vectorized version duration: {1000*(end-start):.4f} ms")

del(a);del(b) # remove the big arrays from memory

my_dot(a,b) = 2500155.0737
Loop version duration: 1065.7761 ms
np.dot(a,b) = 2500155.0737
Vectorized version duration: 1.6682 ms


In [7]:
X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X, w)
X.shape

(4, 1)

In [9]:
X = np.arange(20).reshape(-1, 10)
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [10]:
X[:, 1:3:1]

array([[ 1,  2],
       [11, 12]])

In [11]:
X[0, 1:3:1]

array([1, 2])