In [18]:
import numpy as np
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

## Initializing the weights and bias parameters

In [22]:
b_init = 785.1811367994083
w_init = np.array([0.39133535, 18.75376741, -53.36032453, -26.42131618])

In [23]:
def predict_single_loop(x, w, b):
    """single predict using linear regression

    Args:
        x (ndarray): Shape (n,) example with multiple features
        w (ndarray): Shape (n,) model parameters
        b (scalar): model parameter
        
    Returns:
        p (scalar): prediction
    """
    n = x.shape[0]
    p=0
    for i in range(n):
        p_i = x[i] * w[i]
        p = p + p_i
    p = p + b
    return p

In [24]:
predict_single_loop(X_train, w_init, b_init)

array([-17299.1111338 ,    736.67846672,    769.71968244,   -314.6694346 ])

In [25]:
x_vec = X_train[0,:]
f_wb = predict_single_loop(x_vec, w_init, b_init)
print(f_wb)

459.9999976194083


In [26]:
x_vec

array([2104,    5,    1,   45])

In [27]:
w_init

array([  0.39133535,  18.75376741, -53.36032453, -26.42131618])

In [28]:
np.dot(x_vec, w_init) + b_init

np.float64(459.9999976194083)

In [29]:
def predict(x, w, b):
    """single predict using linear regression

    Args:
        x (ndarray): Shape (n,) example with multiple features
        w (ndarray): Shape (n,) model parameters
        b (scalar): model parameter
        
    Return:
        p (scalar): prediction
    """
    p = np.dot(x, w) + b
    return p

In [30]:
print(predict(x_vec, w_init, b_init))

459.9999976194083


## Compute Cost with Multiple Variables

In [31]:
def compute_cost(X, y, w, b):
    """compute cost

    Args:
        X (ndarray (m,n)): Data, m examples with n features
        y (ndarray (m,)): target values
        w (ndarray (n,)): model parameters
        b (scalar): model parameter
        
    Returns:
        cost(scalar): cost
    """
    m = X.shape[0]
    cost = 0.0
    for i in range(m):
        y_hat = np.dot(X[i], w) + b
        cost = cost + (y_hat - y[i])**2
    cost = cost/(2*m)
    return cost

In [32]:
cost = compute_cost(X_train, y_train, w_init, b_init)
print(cost)

1.5578904045996674e-12


## Gradient Descent with Multiple Variables